from typing import Optional, Literal, List, Union

import truststore

from pydantic_models.api_v4 import (
    DeviceListV4,
    InverterDetailsV4,
    StorageDetailsV4,
    SphDetailsV4,
    SpaDetailsV4,
    MinDetailsV4,
    WitDetailsV4,
    SphsDetailsV4,
    NoahDetailsV4,
    MaxDetailsV4,
)

truststore.inject_into_ssl()
from session import GrowattApiSession  # noqa: E402


NEW_API_ERROR_CODES = {  # TODO use this for something?
    0: "Normal",
    1: "System Error",
    2: "Invalid Secret Token",
    3: "Device Permission Verification Failed",
    4: "Device Not Found",
    5: "Device Offline",
    6: "Failed to Set Parameters",
    7: "Device Type Error",
    8: "Device SN is Empty",
    9: "Date Cannot Be Empty",
    10: "Page Number Cannot Be Empty",
    11: "Device SN Exceeds Quantity Limit",
    12: "No Permission to Access Device",
    100: "API Access Interval",
    101: "No Permission to Access",
    102: "Access Frequency Limit, Different Interfaces Have Different Time Limits",
    -1: "Please Use the New Domain for Access",
}

DeviceType = Literal["inv", "storage", "max", "sph", "spa", "min", "wit", "sph-s", "noah"]


class ApiV4:
    """
    New API (v4)
    https://www.showdoc.com.cn/2540838290984246/11292912972201443
    """

    # TODO refactor - we do not want a v4 package (at least not external) - distribute to corresponding "device_type" packages

    # TODO v4 error codes
    # https://www.showdoc.com.cn/2540838290984246/11292913883034530

    session: GrowattApiSession

    def __init__(self, session: GrowattApiSession) -> None:
        self.session = session
        self.session.api_url = f"{self.session.server_url}/v4"  # FIXME - is this a good idea? or does it change the session object for v1 modules, too?

    def list(
        self,
        page: Optional[int] = None,
    ) -> DeviceListV4:
        """
        Device List
        Retrieve the list of devices associated with the distributor, installer, and terminal account of the secret token.
        The devices obtained through this interface are the only ones allowed to fetch data from.
        Devices not on the list are not permitted to retrieve data.
        https://www.showdoc.com.cn/2540838290984246/11292915113214428

        Returned "device_type" values are: (according to https://www.showdoc.com.cn/2540838290984246/11292914311318022 and https://www.showdoc.com.cn/p/b42ee029e131c68c4dbfdd89285c0ec1)
        * inv
        * storage
        * max
        * sph
        * spa
        * min
        * wit
        * sph-s
        * noah

        Rate limit(s):
        * Fetch frequency is limited to once every 5 seconds.

        Args:
            page (Optional[int]): Page number, default 1 (1~n)

        Returns:
            DeviceList
            {   'data': {   'count': 7,
                            'data': [   {'create_date': datetime.datetime(2021, 6, 29, 12, 2, 46), 'datalogger_sn': None, 'device_sn': 'HPJ0BF20FU', 'device_type': 'max'},
                                        {'create_date': datetime.datetime(2024, 11, 30, 17, 37, 26), 'datalogger_sn': 'QMN000BZP0000000', 'device_sn': 'BZP0000000', 'device_type': 'min'}
                                        {'create_date': datetime.datetime(2017, 1, 18, 14, 9, 53), 'datalogger_sn': None, 'device_sn': 'PR34211399', 'device_type': 'inv'}],
                            'last_pager': True,
                            'not_pager': False,
                            'other': None,
                            'page_size': 100,
                            'pages': 1,
                            'start_count': 0},
                'error_code': 0,
                'error_msg': 'SUCCESSFUL_OPERATION'}
        """

        response = self.session.post(
            endpoint="new-api/queryDeviceList",
            params={"page": page},
        )

        return DeviceListV4.model_validate(response)

    def details(  # noqa: C901 'ApiV4.details' is too complex (11)
        self,
        device_sn: Union[str, List[str]],
        device_type: DeviceType,
    ) -> Union[
        InverterDetailsV4,
        StorageDetailsV4,
        MaxDetailsV4,
        SphDetailsV4,
        SpaDetailsV4,
        MinDetailsV4,
        WitDetailsV4,
        SphsDetailsV4,
        NoahDetailsV4,
    ]:
        """
        Batch device information
        Retrieve basic information of devices in bulk based on device type and device SN.
        The data returned by the interface will only include devices that the key token has permission to access.
        Information about devices without permission will not be returned.
        https://www.showdoc.com.cn/2540838290984246/11292915673945114

        Rate limit(s):
        * The retrieval frequency is once every 5 minutes.

        Args:
            device_sn (Union[str, List[str]]): Inverter serial number or list of (multiple) inverter serial numbers (max 100)
            device_type (DeviceType): Device type (as returned by list())

        Returns:
            Union[InverterDetailsV4, StorageDetailsV4, MaxDetailsV4, SphDetailsV4, SpaDetailsV4, MinDetailsV4, WitDetailsV4, SphsDetailsV4, NoahDetailsV4]

            InverterDetailsV4:
            {   'data': {   'inv': [   {   'address': 1,
                                           'alias': 'HPB3744071',
                                           'big_device': False,
                                           'children': None,
                                           'communication_version': None,
                                           'create_date': None,
                                           'datalogger_sn': 'JPC2101182',
                                           'device_type': 0,
                                           'e_today': 0.0,
                                           'e_total': 0.0,
                                           'energy_day': 0.0,
                                           'energy_day_map': {},
                                           'energy_month': 0.0,
                                           'energy_month_text': '0',
                                           'fw_version': 'AH1.0',
                                           'group_id': 0,
                                           'id': 7,
                                           'img_path': './css/img/status_gray.gif',
                                           'inner_version': 'ahbb1916',
                                           'inv_set_bean': None,
                                           'inverter_info_status_css': 'vsts_table_ash',
                                           'ipm_temperature': 0.0,
                                           'last_update_time': 1613805596000,
                                           'last_update_time_text': datetime.datetime(2021, 2, 20, 15, 19, 56),
                                           'level': 4,
                                           'load_text': '0%',
                                           'location': '在这',
                                           'lost': True,
                                           'model': 269545841,
                                           'model_text': 'A1B0D1T0PFU1M7S1',
                                           'nominal_power': 6000,
                                           'optimizer_list': None,
                                           'parent_id': 'LIST_JPC2101182_0',
                                           'plant_id': 0,
                                           'plant_name': None,
                                           'power': 0.0,
                                           'power_max': None,
                                           'power_max_text': None,
                                           'power_max_time': None,
                                           'record': None,
                                           'rf_stick': None,
                                           'serial_num': 'HPB3744071',
                                           'status': -1,
                                           'status_text': 'inverter.status.lost',
                                           'tcp_server_ip': '192.168.3.35',
                                           'temperature': 0.0,
                                           'tree_id': 'HPB3744071',
                                           'tree_name': 'HPB3744071',
                                           'update_exist': False,
                                           'updating': False,
                                           'user_id': 0,
                                           'user_name': None}]},
                'error_code': 0,
                'error_msg': 'SUCCESSFUL_OPERATION'}

            StorageDetailsV4:
            {   'data': {   'storage': [   {   'ac_in_model': 1.0,
                                               'ac_max_charge_curr': 60.0,
                                               'address': 0,
                                               'alias': None,
                                               'b_light_en': 1,
                                               'bat_low_to_uti_volt': 46.0,
                                               'battery_type': 0,
                                               'battery_undervoltage_cutoff_point': 42.0,
                                               'bulk_charge_volt': 56.4,
                                               'buzzer_en': 1,
                                               'charge_config': 1,
                                               'children': None,
                                               'communication_version': None,
                                               'datalogger_sn': 'EAP0D9M006',
                                               'device_type': 6,
                                               'dtc': 20806,
                                               'float_charge_volt': 54.0,
                                               'fw_version': '141.00/142.00',
                                               'group_id': -1,
                                               'img_path': './css/img/status_gray.gif',
                                               'inner_version': 'null',
                                               'last_update_time': 1718612986000,
                                               'last_update_time_text': datetime.datetime(2024, 6, 17, 16, 29, 46),
                                               'level': 4,
                                               'li_battery_protocol_type': 1,
                                               'location': None,
                                               'lost': True,
                                               'mains_to_battery_operat_point': 54.0,
                                               'manual_start_en': 0.0,
                                               'max_charge_curr': 0.0,
                                               'model': 120,
                                               'model_text': 'A0B0D0T0P0U0M7S8',
                                               'output_config': 3.0,
                                               'output_freq_type': 0,
                                               'output_volt_type': 1,
                                               'over_load_restart': 1.0,
                                               'over_temp_restart': 1.0,
                                               'p_charge': 0.0,
                                               'p_discharge': 0.0,
                                               'parent_id': 'LIST_EAP0D9M006_96',
                                               'plant_id': 0,
                                               'plant_name': None,
                                               'port_name': None,
                                               'pow_saving_en': 0,
                                               'pv_model': 0,
                                               'rate_va': 12000.0,
                                               'rate_watt': 12000.0,
                                               'record': None,
                                               'sci_loss_chk_en': 0,
                                               'serial_num': 'KHMOCM5688',
                                               'status': -1,
                                               'status_led1': False,
                                               'status_led2': False,
                                               'status_led3': False,
                                               'status_led4': False,
                                               'status_led5': False,
                                               'status_led6': False,
                                               'status_text': 'inverter.status.lost',
                                               'sys_time': datetime.datetime(2024, 6, 17, 16, 17),
                                               'tcp_server_ip': '127.0.0.1',
                                               'timezone': 8.0,
                                               'tree_id': 'ST_KHMOCM5688',
                                               'tree_name': None,
                                               'updating': False,
                                               'user_name': None,
                                               'uti_charge_end': 0.0,
                                               'uti_charge_start': 0.0,
                                               'uti_out_end': 0.0,
                                               'uti_out_start': 0.0,
                                               'uw_bat_type2': 1,
                                               'uw_feed_en': 0,
                                               'uw_feed_range': 0.0,
                                               'uw_load_first': 0.0}]},
                'error_code': 0,
                'error_msg': 'SUCCESSFUL_OPERATION'}

            MaxDetailsV4:
            {   'data': {   'max': [   {   'active_rate': 0.0,
                                           'address': 1,
                                           'alias': 'HPJ0BF20FU',
                                           'backflow_default_power': 0.0,
                                           'big_device': False,
                                           'children': None,
                                           'communication_version': 'ZBab-0002',
                                           'datalogger_sn': 'BLE4BEQ0BW',
                                           'device_type': 1,
                                           'dtc': 5001,
                                           'e_today': 0.0,
                                           'e_total': 0.0,
                                           'energy_day': 0.0,
                                           'energy_day_map': {},
                                           'energy_month': 0.0,
                                           'energy_month_text': '0',
                                           'export_limit': 0.0,
                                           'export_limit_power_rate': 0.0,
                                           'fac_high': 0.0,
                                           'fac_low': 0.0,
                                           'frequency_high_limit': 0.0,
                                           'frequency_low_limit': 0.0,
                                           'fw_version': 'TJ1.0',
                                           'group_id': -1,
                                           'id': 0,
                                           'img_path': './css/img/status_gray.gif',
                                           'inner_version': 'TJAA08020002',
                                           'last_update_time': 1716534733000,
                                           'last_update_time_text': datetime.datetime(2024, 5, 24, 15, 12, 13),
                                           'lcd_language': 0,
                                           'level': 6,
                                           'location': None,
                                           'lost': False,
                                           'max_set_bean': None,
                                           'model': 720575940631003386,
                                           'model_text': 'S0AB00D00T00P0FU01M00FA',
                                           'normal_power': 25000.0,
                                           'on_off': False,
                                           'parent_id': 'LIST_BLE4BEQ0BW_3',
                                           'pf': 0.0,
                                           'pf_model': 0,
                                           'pflinep1_lp': 0.0,
                                           'pflinep1_pf': 0.0,
                                           'pflinep2_lp': 0.0,
                                           'pflinep2_pf': 0.0,
                                           'pflinep3_lp': 0.0,
                                           'pflinep3_pf': 0.0,
                                           'pflinep4_lp': 0.0,
                                           'pflinep4_pf': 0.0,
                                           'plant_id': 0,
                                           'plant_name': None,
                                           'port_name': 'ShinePano - BLE4BEQ0BW',
                                           'power': 0.0,
                                           'power_max': None,
                                           'power_max_text': None,
                                           'power_max_time': None,
                                           'pv_pf_cmd_memory_state': 0,
                                           'reactive_rate': 0.0,
                                           'record': None,
                                           'serial_num': 'HPJ0BF20FU',
                                           'status': 1,
                                           'status_text': 'max.status.normal',
                                           'str_num': 0,
                                           'sys_time': None,
                                           'tcp_server_ip': '47.119.22.101',
                                           'timezone': 8.0,
                                           'tree_id': 'HPJ0BF20FU',
                                           'tree_name': 'HPJ0BF20FU',
                                           'updating': False,
                                           'user_name': None,
                                           'vac_high': 0.0,
                                           'vac_low': 0.0,
                                           'voltage_high_limit': 0.0,
                                           'voltage_low_limit': 0.0}]},
                'error_code': 0,
                'error_msg': 'SUCCESSFUL_OPERATION'}

            SphDetailsV4:
            {   'data': {   'sph': [   {   'ac_charge_enable': False,
                                           'active_rate': 100,
                                           'address': 1,
                                           'alias': 'OZD0849010',
                                           'back_up_en': 0,
                                           'backflow_setting': None,
                                           'bat_aging_test_step': 0,
                                           'bat_first_switch1': 0,
                                           'bat_first_switch2': 0,
                                           'bat_first_switch3': 0,
                                           'bat_parallel_num': 0,
                                           'bat_series_num': 0,
                                           'bat_sys_rate_energy': -0.1,
                                           'bat_temp_lower_limit_c': 110.0,
                                           'bat_temp_lower_limit_d': 110.0,
                                           'bat_temp_upper_limit_c': 60.0,
                                           'bat_temp_upper_limit_d': 70.0,
                                           'battery_type': 0,
                                           'baudrate': 0,
                                           'bct_adjust': 0,
                                           'bct_mode': 0,
                                           'buck_ups_fun_en': False,
                                           'buck_ups_volt_set': 0.0,
                                           'cc_current': 0.0,
                                           'charge_power_command': 100,
                                           'charge_time1': None,
                                           'charge_time2': None,
                                           'charge_time3': None,
                                           'children': None,
                                           'com_address': 1,
                                           'communication_version': None,
                                           'country_selected': 0,
                                           'cv_voltage': 0.0,
                                           'datalogger_sn': 'JAD084800B',
                                           'device_type': 0,
                                           'discharge_power_command': 100,
                                           'discharge_time1': None,
                                           'discharge_time2': None,
                                           'discharge_time3': None,
                                           'dtc': 3501,
                                           'energy_day': 0.0,
                                           'energy_day_map': {},
                                           'energy_month': 0.0,
                                           'energy_month_text': '0',
                                           'eps_freq_set': 0,
                                           'eps_fun_en': True,
                                           'eps_volt_set': 0,
                                           'export_limit': 0,
                                           'export_limit_power_rate': 0.0,
                                           'failsafe': 0,
                                           'float_charge_current_limit': 660.0,
                                           'forced_charge_stop_switch1': True,
                                           'forced_charge_stop_switch2': False,
                                           'forced_charge_stop_switch3': False,
                                           'forced_charge_stop_switch4': False,
                                           'forced_charge_stop_switch5': False,
                                           'forced_charge_stop_switch6': False,
                                           'forced_charge_time_start1': datetime.time(0, 0),
                                           'forced_charge_time_start2': datetime.time(0, 0),
                                           'forced_charge_time_start3': datetime.time(0, 0),
                                           'forced_charge_time_start4': datetime.time(0, 0),
                                           'forced_charge_time_start5': datetime.time(0, 0),
                                           'forced_charge_time_start6': datetime.time(0, 0),
                                           'forced_charge_time_stop1': datetime.time(0, 0),
                                           'forced_charge_time_stop2': datetime.time(0, 0),
                                           'forced_charge_time_stop3': datetime.time(0, 0),
                                           'forced_charge_time_stop4': datetime.time(0, 0),
                                           'forced_charge_time_stop5': datetime.time(0, 0),
                                           'forced_charge_time_stop6': datetime.time(0, 0),
                                           'forced_discharge_stop_switch1': False,
                                           'forced_discharge_stop_switch2': False,
                                           'forced_discharge_stop_switch3': False,
                                           'forced_discharge_stop_switch4': False,
                                           'forced_discharge_stop_switch5': False,
                                           'forced_discharge_stop_switch6': False,
                                           'forced_discharge_time_start1': datetime.time(0, 0),
                                           'forced_discharge_time_start2': datetime.time(0, 0),
                                           'forced_discharge_time_start3': datetime.time(0, 0),
                                           'forced_discharge_time_start4': datetime.time(0, 0),
                                           'forced_discharge_time_start5': datetime.time(0, 0),
                                           'forced_discharge_time_start6': datetime.time(0, 0),
                                           'forced_discharge_time_stop1': datetime.time(0, 0),
                                           'forced_discharge_time_stop2': datetime.time(0, 0),
                                           'forced_discharge_time_stop3': datetime.time(0, 0),
                                           'forced_discharge_time_stop4': datetime.time(0, 0),
                                           'forced_discharge_time_stop5': datetime.time(0, 0),
                                           'forced_discharge_time_stop6': datetime.time(0, 0),
                                           'fw_version': 'RA1.0',
                                           'grid_first_switch1': False,
                                           'grid_first_switch2': False,
                                           'grid_first_switch3': False,
                                           'group_id': -1,
                                           'id': 0,
                                           'img_path': './css/img/status_green.gif',
                                           'in_power': 20.0,
                                           'inner_version': 'raab010101',
                                           'inv_version': 0,
                                           'last_update_time': 1716535653000,
                                           'last_update_time_text': datetime.datetime(2024, 5, 24, 15, 27, 33),
                                           'lcd_language': 1,
                                           'level': 4,
                                           'load_first_control': 0,
                                           'load_first_stop_soc_set': 0,
                                           'location': None,
                                           'lost': False,
                                           'lv_voltage': 0.0,
                                           'manufacturer': '   New Energy   ',
                                           'mc_version': 'null',
                                           'mix_ac_discharge_frequency': None,
                                           'mix_ac_discharge_voltage': None,
                                           'mix_off_grid_enable': None,
                                           'modbus_version': 305,
                                           'model': 1159635200000,
                                           'model_text': 'A0B0DBT0PFU2M4S0',
                                           'monitor_version': 'null',
                                           'new_sw_version_flag': 0,
                                           'off_grid_discharge_soc': -1,
                                           'old_error_flag': 0,
                                           'on_off': False,
                                           'out_power': 20.0,
                                           'p_charge': 0,
                                           'p_discharge': 0,
                                           'parent_id': 'LIST_JAD084800B_96',
                                           'pf_sys_year': None,
                                           'plant_id': 0,
                                           'plant_name': None,
                                           'pmax': 0,
                                           'port_name': 'ShinePano - JAD084800B',
                                           'power_factor': 0.0,
                                           'power_max': None,
                                           'power_max_text': None,
                                           'power_max_time': None,
                                           'priority_choose': 1,
                                           'pv_active_p_rate': None,
                                           'pv_grid_voltage_high': None,
                                           'pv_grid_voltage_low': None,
                                           'pv_on_off': None,
                                           'pv_pf_cmd_memory_state': None,
                                           'pv_pf_cmd_memory_state_mix': None,
                                           'pv_pf_cmd_memory_state_sph': False,
                                           'pv_power_factor': None,
                                           'pv_reactive_p_rate': None,
                                           'pv_reactive_p_rate_two': None,
                                           'reactive_delay': 150.0,
                                           'reactive_power_limit': 48.0,
                                           'reactive_rate': 100,
                                           'record': None,
                                           'region': -1,
                                           'safety': '00',
                                           'safety_num': '4E',
                                           'serial_num': 'OZD0849010',
                                           'sgip_en': False,
                                           'single_export': 0,
                                           'status': 5,
                                           'status_text': 'mix.status.normal',
                                           'sys_time': datetime.datetime(2024, 5, 24, 5, 20, 52),
                                           'sys_time_text': datetime.datetime(2024, 5, 24, 5, 20, 52),
                                           'tcp_server_ip': '47.119.173.58',
                                           'timezone': 8.0,
                                           'tree_id': 'ST_OZD0849010',
                                           'tree_name': 'OZD0849010',
                                           'under_excited': 0,
                                           'updating': False,
                                           'user_name': None,
                                           'usp_freq_set': 0,
                                           'uw_grid_watt_delay': 0.0,
                                           'uw_hf_rt2_ee': 0.0,
                                           'uw_hf_rt_ee': 0.0,
                                           'uw_hf_rt_time2_ee': 0.0,
                                           'uw_hf_rt_time_ee': 0.0,
                                           'uw_hv_rt2_ee': 0.0,
                                           'uw_hv_rt_ee': 0.0,
                                           'uw_hv_rt_time2_ee': 0.0,
                                           'uw_hv_rt_time_ee': 0.0,
                                           'uw_lf_rt2_ee': 0.0,
                                           'uw_lf_rt_ee': 0.0,
                                           'uw_lf_rt_time2_ee': 0.0,
                                           'uw_lf_rt_time_ee': 0.0,
                                           'uw_lv_rt2_ee': 0.0,
                                           'uw_lv_rt3_ee': 0.0,
                                           'uw_lv_rt_ee': 0.0,
                                           'uw_lv_rt_time2_ee': 0.0,
                                           'uw_lv_rt_time3_ee': 0.0,
                                           'uw_lv_rt_time_ee': 0.0,
                                           'uw_nominal_grid_volt': 0.0,
                                           'uw_reconnect_start_slope': 0.0,
                                           'v1': 122.0,
                                           'v2': 119.0,
                                           'v3': 146.0,
                                           'v4': 143.0,
                                           'vbat_start_for_charge': 54.4,
                                           'vbat_start_for_discharge': 44.0,
                                           'vbat_stop_for_charge': 5.75,
                                           'vbat_stop_for_discharge': 4.7,
                                           'vbat_warn_clr': 5.0,
                                           'vbat_warning': 440.0,
                                           'vnormal': 360.0,
                                           'voltage_high_limit': 263.0,
                                           'voltage_low_limit': 186.0,
                                           'vpp_open': 0.0,
                                           'wcharge_soc_low_limit1': 100,
                                           'wcharge_soc_low_limit2': 100,
                                           'wdis_charge_soc_low_limit1': 100,
                                           'wdis_charge_soc_low_limit2': 5}]},
                'error_code': 0,
                'error_msg': 'SUCCESSFUL_OPERATION'}

            SpaDetailsV4:
            {   'data': {   'spa': [   {   'ac_charge_enable': False,
                                           'active_p_rate': 100,
                                           'address': 1,
                                           'alias': 'CHENYINSHU',
                                           'backflow_setting': None,
                                           'bat_aging_test_step': 0,
                                           'bat_first_switch1': 0,
                                           'bat_first_switch2': 0,
                                           'bat_first_switch3': 0,
                                           'bat_pack_num': 0,
                                           'bat_serial_num': None,
                                           'bat_sys_rate_energy': 0.0,
                                           'bat_temp_lower_limit_c': 101.0,
                                           'bat_temp_lower_limit_d': 110.0,
                                           'bat_temp_upper_limit_c': 60.0,
                                           'bat_temp_upper_limit_d': 70.0,
                                           'battery_type': 1,
                                           'baudrate': 0,
                                           'bct_adjust': 0,
                                           'bct_mode': 0,
                                           'buck_ups_fun_en': True,
                                           'buck_ups_volt_set': 0.0,
                                           'charge_power_command': 100,
                                           'charge_time1': None,
                                           'charge_time2': None,
                                           'charge_time3': None,
                                           'children': None,
                                           'com_address': 1,
                                           'communication_version': None,
                                           'country_selected': 0,
                                           'datalogger_sn': 'BQC0733006',
                                           'device_type': 0,
                                           'discharge_power_command': 100,
                                           'discharge_time1': None,
                                           'discharge_time2': None,
                                           'discharge_time3': None,
                                           'dtc': 3701,
                                           'energy_day': 0.0,
                                           'energy_day_map': {},
                                           'energy_month': 0.0,
                                           'energy_month_text': '0',
                                           'eps_freq_set': 0,
                                           'eps_fun_en': False,
                                           'eps_volt_set': 0,
                                           'equipment_type': None,
                                           'export_limit': 0.0,
                                           'export_limit_power_rate': 0.0,
                                           'failsafe': 0,
                                           'float_charge_current_limit': 450.0,
                                           'forced_charge_stop_switch4': False,
                                           'forced_charge_stop_switch5': False,
                                           'forced_charge_stop_switch6': False,
                                           'forced_charge_time_start1': datetime.time(0, 0),
                                           'forced_charge_time_start2': datetime.time(0, 0),
                                           'forced_charge_time_start3': datetime.time(0, 0),
                                           'forced_charge_time_start4': None,
                                           'forced_charge_time_start5': None,
                                           'forced_charge_time_start6': None,
                                           'forced_charge_time_stop1': datetime.time(23, 59),
                                           'forced_charge_time_stop2': datetime.time(0, 0),
                                           'forced_charge_time_stop3': datetime.time(0, 0),
                                           'forced_charge_time_stop4': None,
                                           'forced_charge_time_stop5': None,
                                           'forced_charge_time_stop6': None,
                                           'forced_discharge_stop_switch4': False,
                                           'forced_discharge_stop_switch5': False,
                                           'forced_discharge_stop_switch6': False,
                                           'forced_discharge_time_start1': datetime.time(0, 0),
                                           'forced_discharge_time_start2': datetime.time(0, 0),
                                           'forced_discharge_time_start3': datetime.time(0, 0),
                                           'forced_discharge_time_start4': None,
                                           'forced_discharge_time_start5': None,
                                           'forced_discharge_time_start6': None,
                                           'forced_discharge_time_stop1': datetime.time(23, 59),
                                           'forced_discharge_time_stop2': datetime.time(0, 0),
                                           'forced_discharge_time_stop3': datetime.time(0, 0),
                                           'forced_discharge_time_stop4': None,
                                           'forced_discharge_time_stop5': None,
                                           'forced_discharge_time_stop6': None,
                                           'fw_version': 'RH1.0',
                                           'grid_first_switch1': True,
                                           'grid_first_switch2': False,
                                           'grid_first_switch3': False,
                                           'group_id': -1,
                                           'id': 0,
                                           'img_path': './css/img/status_gray.gif',
                                           'inner_version': 'rHBA020202',
                                           'inv_version': 0,
                                           'last_update_time': 1558437021000,
                                           'last_update_time_text': datetime.datetime(2019, 5, 21, 19, 10, 21),
                                           'lcd_language': 1,
                                           'level': 4,
                                           'load_first_start_time1': datetime.time(0, 40),
                                           'load_first_start_time2': datetime.time(0, 0),
                                           'load_first_start_time3': datetime.time(0, 30),
                                           'load_first_stop_time1': datetime.time(0, 49),
                                           'load_first_stop_time2': datetime.time(0, 9),
                                           'load_first_stop_time3': datetime.time(0, 39),
                                           'load_first_switch1': False,
                                           'load_first_switch2': False,
                                           'load_first_switch3': False,
                                           'location': None,
                                           'lost': True,
                                           'manufacturer': '   New Energy   ',
                                           'mc_version': None,
                                           'modbus_version': 305,
                                           'model': 1814994400000,
                                           'model_text': 'A0B1D1T4PFU2M3S8',
                                           'monitor_version': None,
                                           'new_sw_version_flag': 0,
                                           'off_grid_discharge_soc': 0.0,
                                           'old_error_flag': 0,
                                           'on_off': True,
                                           'p_charge': 0.0,
                                           'p_discharge': 0.0,
                                           'parent_id': 'LIST_BQC0733006_96',
                                           'pf_cmd_memory_state': 0,
                                           'pf_sys_year': None,
                                           'plant_id': 0,
                                           'plant_name': None,
                                           'pmax': 3680,
                                           'port_name': 'ShinePano - BQC0733006',
                                           'power_factor': 20000.0,
                                           'power_max': None,
                                           'power_max_text': None,
                                           'power_max_time': None,
                                           'priority_choose': 2,
                                           'pro_pto': 0.0,
                                           'pv_active_p_rate': None,
                                           'pv_grid_voltage_high': None,
                                           'pv_grid_voltage_low': None,
                                           'pv_on_off': None,
                                           'pv_pf_cmd_memory_state': None,
                                           'pv_power_factor': None,
                                           'pv_reactive_p_rate': None,
                                           'pv_reactive_p_rate_two': None,
                                           'reactive_p_rate': 100,
                                           'record': None,
                                           'region': 0,
                                           'safety_correspond_num': 0,
                                           'safety_version': 0,
                                           'serial_num': 'CHENYINSHU',
                                           'spa_ac_discharge_frequency': None,
                                           'spa_ac_discharge_voltage': None,
                                           'spa_off_grid_enable': None,
                                           'status': -1,
                                           'status_text': 'spa.status.lost',
                                           'sys_time': datetime.datetime(2019, 5, 21, 16, 19),
                                           'sys_time_text': datetime.datetime(2019, 5, 21, 16, 19, 22),
                                           'tcp_server_ip': '192.168.3.35',
                                           'timezone': 8.0,
                                           'tree_id': 'ST_CHENYINSHU',
                                           'tree_name': 'CHENYINSHU',
                                           'under_excited': 0,
                                           'updating': False,
                                           'ups_freq_set': 0.0,
                                           'user_name': None,
                                           'vac_high': 262.2,
                                           'vac_low': 184.0,
                                           'vbat_start_for_charge': 57.6,
                                           'vbat_start_for_discharge': 44.0,
                                           'vbat_stop_for_charge': 5.75,
                                           'vbat_stop_for_discharge': 4.7,
                                           'vbat_warn_clr': 5.0,
                                           'vbat_warning': 440.0,
                                           'vpp_open': 0.0,
                                           'w_charge_soc_low_limit1': 100,
                                           'w_charge_soc_low_limit2': 100,
                                           'w_discharge_soc_low_limit1': 100,
                                           'w_discharge_soc_low_limit2': 10,
                                           'w_load_soc_low_limit1': 0,
                                           'w_load_soc_low_limit2': 0}]},
                'error_code': 0,
                'error_msg': 'SUCCESSFUL_OPERATION'}

            MinDetailsV4:
            {   'data': {   'min': [   {   'address': 1,
                                           'alias': 'BZP3N6U09K',
                                           'bat_aging_test_step': 0,
                                           'bat_parallel_num': 0,
                                           'bat_series_num': 0,
                                           'bat_sys_energy': 0.0,
                                           'bat_temp_lower_limit_c': 0.0,
                                           'bat_temp_lower_limit_d': 0.0,
                                           'bat_temp_upper_limit_c': 0.0,
                                           'bat_temp_upper_limit_d': 0.0,
                                           'battery_type': 0,
                                           'baudrate': 0,
                                           'bct_adjust': 0,
                                           'bct_mode': 0,
                                           'bcu_version': None,
                                           'bdc1_model': '0',
                                           'bdc1_sn': None,
                                           'bdc1_version': '\x00\x00\x00\x00-0',
                                           'bdc_auth_version': 0,
                                           'bdc_mode': 0,
                                           'bms_communication_type': 0,
                                           'bms_software_version': None,
                                           'children': None,
                                           'com_address': 1,
                                           'communication_version': 'GJAA-0004',
                                           'country_selected': 1,
                                           'datalogger_sn': 'QMN000BZP3N6U09K',
                                           'device_type': 5,
                                           'dtc': 5203,
                                           'e_today': 0.0,
                                           'e_total': 0.0,
                                           'energy_day_map': {},
                                           'energy_month': 0.0,
                                           'energy_month_text': '0',
                                           'fw_version': 'GJ1.0',
                                           'group_id': -1,
                                           'hw_version': '0',
                                           'id': 1404608,
                                           'img_path': './css/img/status_gray.gif',
                                           'inner_version': 'GJAA04xx',
                                           'last_update_time': 1742876493000,
                                           'last_update_time_text': datetime.datetime(2025, 3, 25, 12, 21, 33),
                                           'level': 4,
                                           'li_battery_fw_version': None,
                                           'li_battery_manufacturers': None,
                                           'location': None,
                                           'lost': False,
                                           'manufacturer': '   PV Inverter  ',
                                           'modbus_version': 0,
                                           'model': 504403158517219338,
                                           'model_text': 'S07B00D00T00P0FU01M000A',
                                           'monitor_version': None,
                                           'mppt': 513.0,
                                           'optimizer_list': None,
                                           'p_charge': 0.0,
                                           'p_discharge': 0.0,
                                           'parent_id': 'LIST_QMN000BZP3N6U09K_22',
                                           'plant_id': 0,
                                           'plantname': None,
                                           'pmax': 1000,
                                           'port_name': 'ShinePano-QMN000BZP3N6U09K',
                                           'power': 0.0,
                                           'power_max': None,
                                           'power_max_text': None,
                                           'power_max_time': None,
                                           'priority_choose': 0,
                                           'pv_num': 0,
                                           'record': None,
                                           'restart_time': 65,
                                           'safety_version': 0,
                                           'serial_num': 'BZP3N6U09K',
                                           'start_time': 65,
                                           'status': 1,
                                           'status_text': 'tlx.status.checking',
                                           'str_num': -1,
                                           'sys_time': None,
                                           'tcp_server_ip': '47.254.132.50',
                                           'timezone': 1.0,
                                           'tlx_set_bean': None,
                                           'tracker_model': 0,
                                           'tree_id': 'ST_BZP3N6U09K',
                                           'tree_name': 'BZP3N6U09K',
                                           'updating': False,
                                           'user_name': None,
                                           'vbat_start_for_discharge': 0.0,
                                           'vbat_stop_for_charge': 0.0,
                                           'vbat_stop_for_discharge': 0.0,
                                           'vbat_warn_clr': 0.0,
                                           'vbat_warning': 0.0,
                                           'vnormal': 280.0,
                                           'vpp_open': 0.0}]},
                'error_code': 0,
                'error_msg': 'SUCCESSFUL_OPERATION'}

            WitDetailsV4:
            {   'data': {   'wit': [   {   'ac_stop_charging_soc': 0.0,
                                           'active_rate': 100.0,
                                           'address': 1,
                                           'alias': 'QWL0DC3002',
                                           'anti_backflow_failure_power_percent': -0.1,
                                           'anti_backflow_failure_time': -1.0,
                                           'anti_backflow_flag': False,
                                           'ats_version': None,
                                           'b_bak_bat2_soc': -1.0,
                                           'b_bak_bat3_soc': -1.0,
                                           'b_bak_soc': 0.0,
                                           'bat_connection_type': 1,
                                           'bat_connection_type2': 0,
                                           'bat_connection_type3': 0,
                                           'bat_serial_num1': None,
                                           'bat_serial_num2': None,
                                           'bat_serial_num3': None,
                                           'bat_serial_num4': None,
                                           'bat_serial_num5': None,
                                           'bat_sleep_wake_up1': 0,
                                           'bat_sleep_wake_up2': 0,
                                           'bat_sleep_wake_up3': 0,
                                           'baudrate': 64,
                                           'bms1_enable': True,
                                           'bms2_enable': False,
                                           'bms3_enable': False,
                                           'charge_soc_limit': 0.0,
                                           'children': None,
                                           'com_address': 1,
                                           'com_name': None,
                                           'communication_version': 'ZBea-0042',
                                           'country_selected': 0,
                                           'datalogger_sn': 'XGD6E7C4S2',
                                           'device_type': 218,
                                           'discharge_soc_limit': 0.0,
                                           'drms_enable': False,
                                           'drms_mode': 0,
                                           'dtc': 5600,
                                           'energy_day': 0.0,
                                           'energy_day_map': {},
                                           'energy_month': 0.0,
                                           'energy_month_text': '0',
                                           'fac_high': 505.0,
                                           'fac_high2': 50.5,
                                           'fac_high3': 50.5,
                                           'fac_low': 475.0,
                                           'fac_low2': 47.5,
                                           'fac_low3': 47.5,
                                           'forced_stop_switch1': False,
                                           'forced_stop_switch2': False,
                                           'forced_stop_switch3': False,
                                           'forced_stop_switch4': False,
                                           'forced_stop_switch5': False,
                                           'forced_stop_switch6': False,
                                           'forced_time_start1': datetime.time(0, 0),
                                           'forced_time_start2': datetime.time(0, 0),
                                           'forced_time_start3': datetime.time(0, 0),
                                           'forced_time_start4': datetime.time(0, 0),
                                           'forced_time_start5': datetime.time(0, 0),
                                           'forced_time_start6': datetime.time(0, 0),
                                           'forced_time_stop1': datetime.time(0, 0),
                                           'forced_time_stop2': datetime.time(0, 0),
                                           'forced_time_stop3': datetime.time(0, 0),
                                           'forced_time_stop4': datetime.time(0, 0),
                                           'forced_time_stop5': datetime.time(0, 0),
                                           'forced_time_stop6': datetime.time(0, 0),
                                           'freq_change_enable': -1,
                                           'freq_high_limit': 50.2,
                                           'freq_low_limit': 49.5,
                                           'fw_version': 'TO1.0',
                                           'grid_meter_enable': True,
                                           'grid_reconnection_time': 300,
                                           'group_id': -1,
                                           'heat_up_time': -1.0,
                                           'hl_voltage_enable': False,
                                           'id': 0,
                                           'img_path': './css/img/status_gray.gif',
                                           'last_update_time': 1728205322000,
                                           'last_update_time_text': datetime.datetime(2024, 10, 6, 17, 2, 2),
                                           'lcd_language': 1,
                                           'level': 4,
                                           'line_n_disconnect_enable': False,
                                           'load_red_rate': -0.1,
                                           'location': None,
                                           'lost': True,
                                           'max_spontaneous_selfuse': 0.0,
                                           'modbus_version': 307,
                                           'model': 2378182293228422120,
                                           'model_text': 'S21B01D00T32P0FU01M03E8',
                                           'module1': 0,
                                           'module2': 0,
                                           'module3': 0,
                                           'module4': 0,
                                           'oil_charge_power_limit': -0.1,
                                           'oil_enable': False,
                                           'oil_rated_power': 0.0,
                                           'on_off': True,
                                           'over_fre_drop_point': 50.3,
                                           'over_fre_lo_red_delay_time': 0.0,
                                           'over_fre_lo_red_res_time': 0.0,
                                           'over_fre_lo_red_slope': 50.0,
                                           'parallel_enable': True,
                                           'param_protect_enable': False,
                                           'parent_id': 'LIST_XGD6E7C4S2_218',
                                           'pf_level1': 0.0,
                                           'pf_level2': 0.0,
                                           'pf_level3': 0.0,
                                           'pf_level4': 0.0,
                                           'pf_level5': 0.0,
                                           'pf_level6': 0.0,
                                           'pf_level7': 0.0,
                                           'pf_level8': 0.0,
                                           'pf_model': 0.0,
                                           'pflinep1_lp': 0.0,
                                           'pflinep1_pf': -1.0,
                                           'pflinep2_lp': 0.0,
                                           'pflinep2_pf': -1.0,
                                           'pflinep3_lp': 0.0,
                                           'pflinep3_pf': -1.0,
                                           'pflinep4_lp': 0.0,
                                           'pflinep4_pf': -1.0,
                                           'plant_id': 0,
                                           'plant_name': None,
                                           'pmax': 100000,
                                           'pmax_level1': 0.0,
                                           'pmax_level2': 0.0,
                                           'pmax_level3': 0.0,
                                           'pmax_level4': 0.0,
                                           'pmax_level5': 0.0,
                                           'pmax_level6': 0.0,
                                           'pmax_level7': 0.0,
                                           'pmax_level8': 0.0,
                                           'port_name': 'ShinePano - XGD6E7C4S2',
                                           'power_factor': 0.5,
                                           'power_imbalance_control_enable': False,
                                           'power_max': None,
                                           'power_max_text': None,
                                           'power_max_time': None,
                                           'power_ud_forced_enable': False,
                                           'pu_enable': 0,
                                           'pv_num': 0,
                                           'pv_pf_cmd_memory_state': False,
                                           'reactive_output_priority': 0,
                                           'reactive_rate': 0.0,
                                           'reactive_value': 0.0,
                                           'record': None,
                                           'restart_time': 30,
                                           'rrcr_enable': 0.0,
                                           'safety_correspond_num': 0.0,
                                           'safety_function': 0,
                                           'safety_version': 0,
                                           'serial_num': 'QWL0DC3002',
                                           'single_export': 1,
                                           'status': -1,
                                           'status_text': 'wit.status.lost',
                                           'str_num': 0,
                                           'svg_function': 0,
                                           'sys_optical_storage_mode': 0,
                                           'sys_time': '2024-10-06 16:27:29',
                                           'sys_time_text': datetime.datetime(2024, 10, 6, 16, 27, 29),
                                           'tcp_server_ip': '127.0.0.1',
                                           'time1_mode': 0,
                                           'time1_power': 0.0,
                                           'time2_mode': 0,
                                           'time2_power': 0.0,
                                           'time3_mode': 0,
                                           'time3_power': 0.0,
                                           'time4_mode': 0,
                                           'time4_power': 0.0,
                                           'time5_mode': 0,
                                           'time5_power': 0.0,
                                           'time6_mode': 0,
                                           'time6_power': 0.0,
                                           'time_start': 30,
                                           'timezone': 8.0,
                                           'tree_id': 'ST_QWL0DC3002',
                                           'tree_name': 'QWL0DC3002',
                                           'underfreq_load_delay_time': 0.0,
                                           'underfreq_load_enable': -1,
                                           'underfreq_load_point': 49.8,
                                           'underfreq_load_res_time': 0.0,
                                           'underfreq_load_slope': 400,
                                           'updating': False,
                                           'user_name': None,
                                           'uw_1th_bat_charge_limit': 100.0,
                                           'uw_1th_bat_discharge_limit': 100.0,
                                           'uw_2th_bat_cap': 9947.0,
                                           'uw_2th_bat_charge_limit': 993.4,
                                           'uw_2th_bat_discharge_limit': 1000.0,
                                           'uw_2th_bat_end_of_vol': 1017.3,
                                           'uw_2th_bat_max_charge_curr': 1021.6,
                                           'uw_2th_bat_max_charge_vol': 1006.9,
                                           'uw_2th_bat_max_discharge_curr': 994.7,
                                           'uw_3th_bat_cap': 10000.0,
                                           'uw_3th_bat_charge_limit': 1000.0,
                                           'uw_3th_bat_discharge_limit': 1000.0,
                                           'uw_3th_bat_end_of_vol': 1000.0,
                                           'uw_3th_bat_max_charge_curr': 1000.0,
                                           'uw_3th_bat_max_charge_vol': 1000.0,
                                           'uw_3th_bat_max_discharge_curr': 1000.0,
                                           'uw_a_couple_enable': -1,
                                           'uw_a_couple_end_soc': -1.0,
                                           'uw_a_couple_start_soc': -1.0,
                                           'uw_ac_charge_enable': True,
                                           'uw_ac_charge_power_rate': 100.0,
                                           'uw_anti_backflow': 1,
                                           'uw_bat_cap': 100.0,
                                           'uw_bat_charge_stop_soc': 100.0,
                                           'uw_bat_charge_stop_soc2': -1.0,
                                           'uw_bat_charge_stop_soc3': -1.0,
                                           'uw_bat_cnn_way': 10000.0,
                                           'uw_bat_discharge_stop_soc': 10.0,
                                           'uw_bat_discharge_stop_soc2': -1.0,
                                           'uw_bat_discharge_stop_soc3': -1.0,
                                           'uw_bat_enable1': False,
                                           'uw_bat_enable2': False,
                                           'uw_bat_enable3': False,
                                           'uw_bat_max_charge_current': 100.0,
                                           'uw_bat_max_discharge_current': 100.0,
                                           'uw_batt_eod_vol': 620.0,
                                           'uw_batt_max_charge_vol': 800.0,
                                           'uw_batt_type1': 0,
                                           'uw_batt_type2': 0,
                                           'uw_batt_type3': 0,
                                           'uw_connect_phase_mode': 1,
                                           'uw_demand_mange_charge_power_limit': 0.0,
                                           'uw_demand_mange_discharge_power_limit': 0.0,
                                           'uw_demand_mange_enable': False,
                                           'uw_dg_start_soc': 60.0,
                                           'uw_dg_stop_soc': 30.0,
                                           'uw_disconnect_phase_mode': 1,
                                           'uw_gen_port_dev_type': 0,
                                           'uw_gen_power': 0.0,
                                           'uw_load_pv_inverter': 0,
                                           'uw_off_grid_enable': False,
                                           'uw_off_grid_freq': 0.0,
                                           'uw_off_grid_soc1': 5.0,
                                           'uw_off_grid_soc2': -1.0,
                                           'uw_off_grid_soc3': -1.0,
                                           'uw_off_grid_vol': 1.0,
                                           'uw_on_off_change_manual_mode': 0,
                                           'uw_on_off_change_mode': 2,
                                           'uw_on_off_grid_set': 0,
                                           'uw_pcs_type': 0,
                                           'v_bak_soc_enable': False,
                                           'vac_high': 438.2,
                                           'vac_high2': 537.8,
                                           'vac_high3': 537.8,
                                           'vac_low': 338.6,
                                           'vac_low2': 199.1,
                                           'vac_low3': 199.1,
                                           'version': 'TOaa211689',
                                           'vnormal': 1.0,
                                           'voltage_high_limit': 438.2,
                                           'voltage_low_limit': 338.6,
                                           'vpv_start': 195.0,
                                           'w_anti_backflow_meter_power_limit': 0.0,
                                           'w_power_restart_slope_ee': 5000.0,
                                           'w_power_start_slope': 5000.0,
                                           'wide_voltage_enable': False}]},
                'error_code': 0,
                'error_msg': 'SUCCESSFUL_OPERATION'}

            SphsDetailsV4:
            TBA

            NoahDetailsV4:
            TBA

        """

        if isinstance(device_sn, list):
            assert len(device_sn) <= 100, "Max 100 devices per request"
            device_sn = ",".join(device_sn)

        response = self.session.post(
            endpoint="new-api/queryDeviceInfo",
            params={
                "deviceSn": device_sn,
                "deviceType": device_type,
            },
        )

        # FIXME DEBUG
        import pprint

        pprint.pprint(response, indent=4, width=500)
        sample_data = """{
    "code": 0,
    "data": {
        "wit": [
            {
                "id": 0,
                "serialNum": "0ZFN00R23ZBF0002",
                "portName": "ShinePano - TTN0D9E01P",
                "dataLogSn": "TTN0D9E01P",
                "sysTime": "2024-05-29 14:00:25",
                "groupId": -1,
                "alias": "0ZFN00R23ZBF0002",
                "location": "",
                "lost": false,
                "lastUpdateTime": 1716963248000,
                "tcpServerIp": "120.25.191.20",
                "status": 1,
                "addr": 5,
                "deviceType": 218,
                "onOff": 1,
                "saftyFunc": 0,
                "pvPfCmdMemoryState": 0,
                "activeRate": 50,
                "reactiveRate": 0,
                "powerFactor": 1.0,
                "pmax": 100000,
                "vnormal": 2.0,
                "fwVersion": "TO1.0",
                "model": 2377905207708287976,
                "comName": "null",
                "comVersion": "ZBea-0037",
                "lcdLanguage": 1,
                "countrySelected": 1,
                "vpvStart": 250.0,
                "timeStart": 30,
                "restartTime": 10,
                "wPowerStartSlope": 50.0,
                "wPowerRestartSlopeEE": 50.0,
                "wselectBaudrate": 0,
                "comAddress": 2,
                "dtc": 5600,
                "vacLow": 276.0,
                "vacHigh": 458.1,
                "facLow": 475.0,
                "facHigh": 525.0,
                "voltageHighLimit": 456.4,
                "voltageLowLimit": 277.7,
                "freqHighLimit": 50.5,
                "freqLowLimit": 47.5,
                "version": "TOaa181390",
                "modbusVersion": 305,
                "pfModel": 0,
                "module4": 0,
                "module3": 0,
                "module2": 0,
                "module1": 0,
                "uwAntiBackflow": 0,
                "wAntiBackflowMeterPowerLimit": 0.0,
                "reactiveValue": 0.0,
                "reactiveOutputPriority": 0,
                "uwOnOffChangeMode": 0,
                "uwPcsType": 1,
                "uwACChargePowerRate": 100,
                "uwBattMaxChargeVol": 854.0,
                "uwBattEODVol": 678.0,
                "uwConnectPhaseMode": 0,
                "uwDisConnectPhaseMode": 0,
                "uwBatMaxChargeCurrent": 140.0,
                "uwBatMaxDisChargeCurrent": 140.0,
                "uwOnOffChangeManualMode": 1,
                "uwOnOffGridSet": 0,
                "uwOffGridVol": 1.0,
                "uwOffGridFreq": 0.0,
                "uwLoadPvInverter": 0,
                "uwACChargeEnable": 1,
                "uwOffGridEnable": 1,
                "uwBatChargeStopSoc": 100,
                "uwBatDisChargeStopSoc": 10,
                "singleExport": 0,
                "forcedTimeStart1": "21:0",
                "forcedTimeStart2": "0:0",
                "forcedTimeStart3": "0:0",
                "forcedTimeStart4": "0:0",
                "forcedTimeStart5": "0:0",
                "forcedTimeStart6": "0:0",
                "forcedTimeStop1": "22:0",
                "forcedTimeStop2": "0:0",
                "forcedTimeStop3": "0:0",
                "forcedTimeStop4": "0:0",
                "forcedTimeStop5": "0:0",
                "forcedTimeStop6": "0:0",
                "time1Mode": 0,
                "time2Mode": 0,
                "time3Mode": 0,
                "time4Mode": 0,
                "time5Mode": 0,
                "time6Mode": 0,
                "forcedStopSwitch1": 0,
                "forcedStopSwitch2": 0,
                "forcedStopSwitch3": 0,
                "forcedStopSwitch4": 0,
                "forcedStopSwitch5": 0,
                "forcedStopSwitch6": 0,
                "pflinep1_lp": 0,
                "pflinep1_pf": -1.0,
                "pflinep2_lp": 0,
                "pflinep2_pf": -1.0,
                "pflinep3_lp": 0,
                "pflinep3_pf": -1.0,
                "pflinep4_lp": 0,
                "pflinep4_pf": -1.0,
                "updating": false,
                "record": null,
                "powerMax": null,
                "powerMaxTime": null,
                "energyDay": 0.0,
                "energyMonth": 0.0,
                "energyDayMap": {},
                "userName": null,
                "modelText": "S21B00D04T30P0FU01M03E8",
                "plantId": 0,
                "plantName": null,
                "timezone": 8.0,
                "sysTimeText": "2024-05-29 14:00:25",
                "uwGenPortDevType": 0,
                "uwGenPower": 0.0,
                "oilEnable": 0,
                "uwDgStartSoc": 20,
                "uwDgStopSoc": 30,
                "uwBattType1": 0,
                "uwBattType2": 0,
                "uwBattType3": 0,
                "uwBatCap": 100,
                "uw2thBatMaxChgVol": 1000.0,
                "uw2thBatEndOfVol": 1000.0,
                "uw2thBatMaxChgCurr": 1000.0,
                "uw2thBatMaxDisChgCurr": 1000.0,
                "uw2thBatCap": 10000,
                "uw2thBatChgLimit": 1000.0,
                "uw2thBatDisChgLimit": 1000.0,
                "uw3thBatMaxChgVol": 1000.0,
                "uw3thBatEndOfVol": 1000.0,
                "uw3thBatMaxChgCurr": 1000.0,
                "uw3thBatMaxDisChgCurr": 1000.0,
                "uw3thBatCap": 10000,
                "uw3thBatChgLimit": 1000.0,
                "uw3thBatDisChgLimit": 1000.0,
                "uwBatCnnWay": 10000,
                "uwACoupleEnable": 0,
                "uwACoupleStartSOC": 0,
                "uwACoupleEndSOC": 0,
                "uw1thBatChgLimit": 0.0,
                "uw1thBatDisChgLimit": 0.1,
                "uwBatEnable1": 0,
                "uwBatEnable2": 0,
                "uwBatEnable3": 0,
                "batSerialNum1": "0WZN00R23ZB0000C",
                "batSerialNum2": "",
                "batSerialNum3": "",
                "batSerialNum4": "",
                "batSerialNum5": ",bdcLinkNum=1,packNum=13",
                "powerMaxText": "",
                "energyMonthText": "0",
                "treeName": "0ZFN00R23ZBF0002",
                "treeID": "ST_0ZFN00R23ZBF0002",
                "parentID": "LIST_TTN0D9E01P_218",
                "imgPath": "./css/img/status_gray.gif",
                "antiBackflowFlag": 0,
                "svgFunction": 0,
                "statusText": "wit.status.operating",
                "lastUpdateTimeText": "2024-05-29 14:14:08",
                "level": 4,
                "children": null
            }
        ]
    },
    "message": "SUCCESSFUL_OPERATION"
}"""

        import json
        import pprint

        j = json.loads(sample_data)
        pprint.pprint(j, indent=4, width=500)
        k = SphsDetailsV4.model_validate(j)  # <-----------------------------
        pprint.pprint(k.model_dump(), indent=4, width=500)
        # FIXME DEBUG
        pprint.pprint(response, indent=4, width=500)
        k2 = SphsDetailsV4.model_validate(response)  # <-----------------------------
        pprint.pprint(k2.model_dump(), indent=4, width=500)

        device_type = device_type.lower()
        if device_type == "inv":
            return InverterDetailsV4.model_validate(response)
        elif device_type == "storage":
            return StorageDetailsV4.model_validate(response)
        elif device_type == "max":
            return MaxDetailsV4.model_validate(response)
        elif device_type == "sph":
            return SphDetailsV4.model_validate(response)
        elif device_type == "spa":
            return SpaDetailsV4.model_validate(response)
        elif device_type == "min":
            return MinDetailsV4.model_validate(response)
        elif device_type == "wit":
            return WitDetailsV4.model_validate(response)
        elif device_type == "sph-s":  # TODO ongoing
            return SphsDetailsV4.model_validate(response)
        elif device_type == "noah":  # TODO
            return NoahDetailsV4.model_validate(response)
        else:
            raise ValueError(f"Unknown device type: {device_type}")
